services:
  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://travel-hub-be.ccrolabs.com/api/v1
    ports:
      - "3013:3000"
    env_file:
      - ./fe/.env.development
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://travel-hub-be.ccrolabs.com/api/v1
    restart: unless-stopped
    container_name: travel-hub-fe
    networks:
      - app-network
    depends_on:
      backend:
        condition: service_healthy

networks:
  app-network:
    driver: bridge