services:
  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "8013:8000"
    env_file:
      - ./be/.env.development
    environment:
      - APP_ENV=production
      - API_V1_STR=/api/v1
      - PROJECT_NAME=Travel-Content-Hub
      - OPENAI_MODEL=gpt-4o-mini
      - BACKEND_CORS_ORIGINS=["https://travel-hub.ccrolabs.com/api/v1", "http://localhost:3013"]
      - SECRET_KEY=${SECRET_KEY}
    restart: unless-stopped
    container_name: travel-hub-be
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
 
  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://travel-hub-be.ccrolabs.com/api/v1
    ports:
      - "3013:3000"
    env_file:
      - ./fe/.env.development
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://travel-hub-be.ccrolabs.com/api/v1
    restart: unless-stopped
    container_name: travel-hub-fe
    networks:
      - app-network
    depends_on:
      backend:
        condition: service_healthy
 
networks:
  app-network:
    driver: bridge